# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py312"

[lint]
select = [
    "ALL",
]

ignore = [
    "ANN101", # Missing type annotation for `self` in method
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "D203", # no-blank-line-before-class (incompatible with formatter)
    "D212", # multi-line-summary-first-line (incompatible with formatter)
    "COM812", # incompatible with formatter
    "ISC001", # incompatible with formatter
    "N806", # non-lowercase-variable-in-function
    "G004", # logging-f-string
    "ERA001", # commented-out-code
    "D101", # undocumented-public-class
    "D102", # undocumented-public-method
    "BLE001", # blind-except
    "DTZ005", #call-datetime-now-without-tzinfo
    "PLR0912", #too-many-branches
    "N802", #invalid-function-name
    "N803", #argumentname must be lowercase
    "N815", #argumentname must be lowercase
    "PLR0913", #too-many-arguments
    "FBT001", # boolean-type-hint-positional-argument
    "FBT002", # boolean-default-value-positional-argument
    "FBT003", # boolean-type-hint-positional-argument
    "TRY400", # error-instead-of-exception
    "TC001", # typing-only-third-party-import
    "TC002", # typing-only-third-party-import
    "RUF012", # mutable-class-default
    "TC003", #typing-only-standard-library-import
    "UP035", #deprecated-import
    "DTZ901", #datetime-min-max
    "EXE002", #shebang-missing-executable-file
    "PLC0415", #import-outside-top-level
    "PGH003", #blanket-type-ignore
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25